server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: 8888
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB